name: Concatenate

on:
  push:
    branches:
      - main

jobs:
  build:
    if: "!contains(github.event.*.labels.*.name, 'automated-pr')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: listup-targets
        run: |
          files=$(find rulesets/ -name "*.yaml" -type f -print)
          escaped_files="${files//$'\n'/\ }"
          echo "files=${escaped_files}" >> $GITHUB_OUTPUT
      - name: Clear concat file
        run: |
          rm ruleset.yaml
      - name: Concatenate files
        uses: ftnext/action-concatenate-files@main
        with:
          sources: ${{ steps.listup-targets.outputs.files }}
          destination: ruleset.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          branch: concat
          commit-message: |
            Concatenate ruleset
            [skip ci]
          labels: |
            automated-pr
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
